version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
        - 8080:80
    volumes:
        - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./conf/conf.d/:/etc/nginx/conf.d/
        - ./:/usr/share/nginx/html
    depends_on:
        - php-fpm
        - php-fpm2
  php-fpm:
    build:
       context: .
       dockerfile: ./Dockerfile/Dockerfile
    ports:
        - 9000:9000
    volumes:
        - ./:/var/www/html
  php-fpm2:
    image: php:7.4-fpm
    ports:
        - 9001:9000
    volumes:
        - ./test:/var/www/html

